# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: neobizdev/ruby24

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - /etc/init.d/mysql start
          - mysql -u root -e 'create database sokuhaku_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci'
          - mysql -u root -e "grant all on sokuhaku_test.* to 'username'@'%' identified by 'password';"
          - bundle install -j4 --path vendor/bundle
          - bundle clean
          - export RAILS_ENV=test
          - bin/rails db:environment:set RAILS_ENV=test
          - bin/rails db:migrate
